### ISSUE TITLE
database.find() should be parsed with metadata

### ISSUE THREAD

**Issue by ribizli** [hbenl/mpc-js-core#3]
Since MPD returns file entries with metadata, they should be mapped to `Song` instead of `File`.

See my problem: listing the songs for an album:

```
mpc.database.find([['Album', 'Album title']])
  .then(r => Promise.all(
    r.map(song => mpc.database.listInfo(song.path).then(info => info[0]))))
```
A lot of unneeded command is sent to MPD...

Also there is some code repeating in the constructors of the different classes (`path`, `lastModified`).

**Comment by hbenl** [comment]
Oops, thanks for spotting this, I fixed it in version 1.1.3.

Regarding the code repetitions: I considered it more trouble than it's worth to unify this, especially since it's only one line (`lastModified`) that's repeated in all constructors - the `path` is available under a different key for directories  and playlists.
